[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:web"]

[start]
cmd = "cd apps/web && npx next start -H 0.0.0.0 -p ${PORT:-3000}"