[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build:web"

# Web Service Configuration
[[services]]
name = "web"
port = 3000
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

# Worker Service Configuration (temporarily disabled)
# [[services]]
# name = "worker"
# startCommand = "pnpm worker:start"

# Environment Variables
[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
ENABLE_AI_INSIGHTS = "true"
ENABLE_REALTIME_COLLAB = "true"
AI_COST_LIMIT_CENTS = "50000"
