[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.worker"

[deploy]
# Worker doesn't need health checks as it's a background service
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Worker specific settings
[environment]
NODE_ENV = "production"