[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build:web"

[deploy]
startCommand = "pnpm start --filter=@consulting-platform/web"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

# Environment Variables
[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
ENABLE_AI_INSIGHTS = "true"
ENABLE_REALTIME_COLLAB = "true"
AI_COST_LIMIT_CENTS = "50000"
