// Auto-generated RSS feed configuration from brief360
// Source: brief360/scripts/seed_rss_feeds.py
// Generated: 2025-01-XX

export interface FeedConfig {
  name: string;
  url: string;
  description: string;
  enabled: boolean;
  feed_type: "rss" | "rsshub" | "api";
  fetch_frequency_minutes: number;
  category: string;
}

// Brief360 RSS Feeds organized by category
export const BRIEF360_FEEDS: Record<string, FeedConfig> = {
  // Security Feeds (15-30 min frequency)
  security_cert_bund: {
    name: "CERT-Bund (German)",
    url: "https://www.cert-bund.de/rss/advisories.rss",
    description: "German CERT security advisories",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_us_cert: {
    name: "US-CERT Alerts",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    description: "US Cybersecurity and Infrastructure Security Agency alerts",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_nist_nvd: {
    name: "NIST NVD",
    url: "https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml",
    description: "National Vulnerability Database RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_exploit_db: {
    name: "Exploit-DB",
    url: "https://www.exploit-db.com/rss.xml",
    description: "Exploit Database RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_krebs: {
    name: "Krebs on Security",
    url: "https://krebsonsecurity.com/feed/",
    description: "Krebs on Security blog feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_schneier: {
    name: "Schneier on Security",
    url: "https://www.schneier.com/feed/atom/",
    description: "Bruce Schneier's security blog",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_hacker_news: {
    name: "The Hacker News",
    url: "https://feeds.feedburner.com/TheHackersNews",
    description: "The Hacker News security feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_bleeping: {
    name: "Bleeping Computer",
    url: "https://www.bleepingcomputer.com/feed/",
    description: "Bleeping Computer security news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_dark_reading: {
    name: "Dark Reading",
    url: "https://www.darkreading.com/rss_simple.asp",
    description: "Dark Reading security news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_threatpost: {
    name: "Threatpost",
    url: "https://threatpost.com/feed/",
    description: "Threatpost security news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_securityweek: {
    name: "SecurityWeek",
    url: "https://www.securityweek.com/feed/",
    description: "SecurityWeek news feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_sans: {
    name: "SANS Internet Storm Center",
    url: "https://isc.sans.edu/rssfeed.xml",
    description: "SANS ISC security feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_cve_details: {
    name: "CVE Details",
    url: "https://www.cvedetails.com/vulnerability-feed.php?vendor_id=0&product_id=0&version_id=0&orderby=3&cvssscoremin=0",
    description: "CVE Details vulnerability feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 15,
    category: "security",
  },
  security_affairs: {
    name: "Security Affairs",
    url: "https://securityaffairs.co/wordpress/feed",
    description: "Security Affairs blog",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "security",
  },
  security_infosec_news: {
    name: "InfoSec News",
    url: "https://www.infosecnews.org/feed/",
    description: "InfoSec News feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "security",
  },
  security_cso: {
    name: "CSO Online",
    url: "https://www.csoonline.com/index.rss",
    description: "CSO Online security news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "security",
  },
  security_helpnet: {
    name: "Help Net Security",
    url: "https://www.helpnetsecurity.com/feed/",
    description: "Help Net Security feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "security",
  },
  security_techtarget: {
    name: "TechTarget",
    url: "https://www.techtarget.com/searchsecurity/rss/RSS2/",
    description: "TechTarget security feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "security",
  },
  security_reddit_netsec: {
    name: "Reddit r/netsec",
    url: "https://rsshub.app/reddit/r/netsec",
    description: "Reddit netsec via RSSHub",
    enabled: true,
    feed_type: "rsshub",
    fetch_frequency_minutes: 30,
    category: "security",
  },
  security_cisco: {
    name: "Cisco Security",
    url: "https://rsshub.app/cisco/security-advisories",
    description: "Cisco Security advisories via RSSHub",
    enabled: true,
    feed_type: "rsshub",
    fetch_frequency_minutes: 60,
    category: "security",
  },
  security_microsoft: {
    name: "Microsoft Security",
    url: "https://rsshub.app/microsoft/security-update",
    description: "Microsoft security updates via RSSHub",
    enabled: true,
    feed_type: "rsshub",
    fetch_frequency_minutes: 60,
    category: "security",
  },

  // News Feeds (30 min frequency)
  news_reuters_top: {
    name: "Reuters Top News",
    url: "https://feeds.reuters.com/reuters/topNews",
    description: "Reuters top news feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_bbc_world: {
    name: "BBC World News",
    url: "http://feeds.bbci.co.uk/news/world/rss.xml",
    description: "BBC World News feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_ap: {
    name: "Associated Press",
    url: "https://rsshub.app/ap/topics/apf-topnews",
    description: "AP news via RSSHub",
    enabled: true,
    feed_type: "rsshub",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_al_jazeera: {
    name: "Al Jazeera",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    description: "Al Jazeera news feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_guardian: {
    name: "The Guardian World",
    url: "https://www.theguardian.com/world/rss",
    description: "The Guardian world news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_tagesschau: {
    name: "Tagesschau",
    url: "https://www.tagesschau.de/xml/rss2/",
    description: "Tagesschau German news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_spiegel: {
    name: "Der Spiegel",
    url: "https://www.spiegel.de/schlagzeilen/index.rss",
    description: "Der Spiegel news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_faz: {
    name: "FAZ Aktuell",
    url: "https://www.faz.net/rss/aktuell/",
    description: "FAZ aktuell news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_sueddeutsche: {
    name: "Süddeutsche Zeitung",
    url: "https://rss.sueddeutsche.de/alles",
    description: "Süddeutsche Zeitung news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_nzz: {
    name: "NZZ",
    url: "https://www.nzz.ch/recent.rss",
    description: "Neue Zürcher Zeitung",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_cnn: {
    name: "CNN Top Stories",
    url: "http://rss.cnn.com/rss/edition.rss",
    description: "CNN top stories",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_npr: {
    name: "NPR News",
    url: "https://feeds.npr.org/1001/rss.xml",
    description: "NPR news feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_pbs: {
    name: "PBS NewsHour",
    url: "https://www.pbs.org/newshour/feeds/rss/news",
    description: "PBS NewsHour feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_nbc: {
    name: "NBC News",
    url: "https://feeds.nbcnews.com/nbcnews/public/news",
    description: "NBC News feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_abc: {
    name: "ABC News",
    url: "https://abcnews.go.com/abcnews/topstories",
    description: "ABC News top stories",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "news",
  },
  news_reddit_worldnews: {
    name: "Reddit r/worldnews",
    url: "https://rsshub.app/reddit/r/worldnews",
    description: "Reddit worldnews via RSSHub",
    enabled: true,
    feed_type: "rsshub",
    fetch_frequency_minutes: 30,
    category: "news",
  },

  // Business Feeds (30-60 min frequency)
  business_reuters: {
    name: "Reuters Business",
    url: "https://feeds.reuters.com/reuters/businessNews",
    description: "Reuters business news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "business",
  },
  business_bbc: {
    name: "BBC Business",
    url: "http://feeds.bbci.co.uk/news/business/rss.xml",
    description: "BBC Business news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "business",
  },
  business_ft: {
    name: "Financial Times",
    url: "https://www.ft.com/?format=rss",
    description: "Financial Times RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "business",
  },
  business_handelsblatt: {
    name: "Handelsblatt",
    url: "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
    description: "Handelsblatt business news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "business",
  },
  business_wiwo: {
    name: "WirtschaftsWoche",
    url: "https://www.wiwo.de/contentexport/feed/rss/schlagzeilen",
    description: "WirtschaftsWoche business news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "business",
  },
  business_bloomberg: {
    name: "Bloomberg Markets",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    description: "Bloomberg markets news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_wsj: {
    name: "WSJ Markets",
    url: "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    description: "Wall Street Journal markets",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_economist: {
    name: "The Economist",
    url: "https://www.economist.com/rss",
    description: "The Economist RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_hbr: {
    name: "Harvard Business Review",
    url: "https://hbr.org/feed",
    description: "HBR RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_marketwatch: {
    name: "MarketWatch",
    url: "http://feeds.marketwatch.com/marketwatch/topstories/",
    description: "MarketWatch top stories",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_seeking_alpha: {
    name: "Seeking Alpha",
    url: "https://seekingalpha.com/feed.xml",
    description: "Seeking Alpha feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_forbes: {
    name: "Forbes Business",
    url: "https://www.forbes.com/business/feed/",
    description: "Forbes business feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_business_insider: {
    name: "Business Insider",
    url: "https://feeds.businessinsider.com/custom/all",
    description: "Business Insider feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_cnbc: {
    name: "CNBC",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
    description: "CNBC news feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_yahoo_finance: {
    name: "Yahoo Finance",
    url: "https://feeds.finance.yahoo.com/rss/2.0/headline",
    description: "Yahoo Finance headlines",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_investopedia: {
    name: "Investopedia",
    url: "https://www.investopedia.com/rss/",
    description: "Investopedia RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "business",
  },
  business_wto: {
    name: "WTO News",
    url: "https://www.wto.org/indexrss.xml",
    description: "World Trade Organization news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "business",
  },
  business_world_bank: {
    name: "World Bank",
    url: "https://www.worldbank.org/en/news/all.rss",
    description: "World Bank news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "business",
  },

  // Technology Feeds (30-60 min frequency)
  tech_techcrunch: {
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    description: "TechCrunch RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_arstechnica: {
    name: "Ars Technica",
    url: "http://feeds.arstechnica.com/arstechnica/index",
    description: "Ars Technica feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_verge: {
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    description: "The Verge RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_wired: {
    name: "Wired",
    url: "https://www.wired.com/feed/rss",
    description: "Wired RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_heise: {
    name: "Heise Online",
    url: "https://www.heise.de/rss/heise-atom.xml",
    description: "Heise Online German tech news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_golem: {
    name: "Golem.de",
    url: "https://rss.golem.de/rss.php?feed=ATOM1.0",
    description: "Golem.de German tech news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_mit_tr: {
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    description: "MIT Technology Review",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_zdnet: {
    name: "ZDNet",
    url: "https://www.zdnet.com/news/rss.xml",
    description: "ZDNet news feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_yc_hn: {
    name: "Hacker News",
    url: "https://news.ycombinator.com/rss",
    description: "Y Combinator Hacker News",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_lobsters: {
    name: "Lobsters",
    url: "https://lobste.rs/rss",
    description: "Lobsters tech community",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 30,
    category: "technology",
  },
  tech_github: {
    name: "GitHub Blog",
    url: "https://github.blog/feed/",
    description: "GitHub Blog RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_stackoverflow: {
    name: "Stack Overflow Blog",
    url: "https://stackoverflow.blog/feed/",
    description: "Stack Overflow blog",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_devto: {
    name: "Dev.to",
    url: "https://dev.to/feed",
    description: "Dev.to community feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_smashing: {
    name: "Smashing Magazine",
    url: "https://www.smashingmagazine.com/feed/",
    description: "Smashing Magazine feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_css_tricks: {
    name: "CSS-Tricks",
    url: "https://css-tricks.com/feed/",
    description: "CSS-Tricks blog",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_ieee: {
    name: "IEEE Spectrum",
    url: "https://spectrum.ieee.org/rss/fulltext",
    description: "IEEE Spectrum feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_nature: {
    name: "Nature News",
    url: "https://www.nature.com/subjects/computer-science.rss",
    description: "Nature computer science news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_science_daily: {
    name: "Science Daily",
    url: "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml",
    description: "Science Daily AI news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_computerworld: {
    name: "Computerworld",
    url: "https://www.computerworld.com/news/rss2/",
    description: "Computerworld news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 60,
    category: "technology",
  },
  tech_reddit_programming: {
    name: "Reddit r/programming",
    url: "https://rsshub.app/reddit/r/programming",
    description: "Reddit programming via RSSHub",
    enabled: true,
    feed_type: "rsshub",
    fetch_frequency_minutes: 30,
    category: "technology",
  },

  // Politics Feeds (120 min frequency)
  politics_whitehouse: {
    name: "White House",
    url: "https://www.whitehouse.gov/feed/",
    description: "White House RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "politics",
  },
  politics_politico: {
    name: "Politico",
    url: "https://www.politico.com/rss/politicopicks.xml",
    description: "Politico RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "politics",
  },
  politics_hill: {
    name: "The Hill",
    url: "https://thehill.com/feed/",
    description: "The Hill political news",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "politics",
  },
  politics_bundestag: {
    name: "Bundestag",
    url: "https://www.bundestag.de/rss/index.rss",
    description: "German Bundestag RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "politics",
  },
  politics_bundesregierung: {
    name: "Bundesregierung",
    url: "https://www.bundesregierung.de/breg-de/service/rss",
    description: "German federal government RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "politics",
  },
  politics_eu_parliament: {
    name: "EU Parliament",
    url: "https://www.europarl.europa.eu/rss/",
    description: "European Parliament RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "politics",
  },

  // Regulation Feeds (120 min frequency)
  regulation_federal_register: {
    name: "US Federal Register",
    url: "https://www.federalregister.gov/documents/search.rss",
    description: "US Federal Register RSS feed",
    enabled: true,
    feed_type: "rss",
    fetch_frequency_minutes: 120,
    category: "regulation",
  },
};

export type Brief360FeedKey = keyof typeof BRIEF360_FEEDS;
